//
//  DocumentListInteractor.swift
//  ViperDemo
//
//  Created Thinh Nguyen on 12/3/17.
//  Copyright © 2017 Prospertin. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DocumentListInteractor: DocumentListInteractorInputProtocol {

    weak var presenter: DocumentListInteractorOutputProtocol?
    
    func retrieveDocuments(query: DocQuery) {
        
    }
}

extension DocumentListInteractor: DataManagerOutputProtocol {
    
    func didRetrieveDocuments(documents: [DocumentModel]) {
        // Do cache Document if needed, create the UI Model and prepare them for data binding etc...
    }
}
