//
//  DocumentListViewController.swift
//  ViperDemo
//
//  Created Thinh Nguyen on 12/3/17.
//  Copyright © 2017 Prospertin. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DocumentListViewController: UIViewController, DocumentListViewProtocol {
    
	var presenter: DocumentListPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter?.presentDocuments()
    }

    func showDocuments(with documentUIList: [DocumentUIModel]) {
        
    }
    
}
