//
//  DocumentListRouter.swift
//  ViperDemo
//
//  Created Thinh Nguyen on 12/3/17.
//  Copyright © 2017 Prospertin. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DocumentListRouter: DocumentListWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DocumentListViewController(nibName: nil, bundle: nil)
        let interactor = DocumentListInteractor()
        let router = DocumentListRouter()
        let presenter = DocumentListPresenter(view: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    /* DocumentListWireframeProtocol */
    func routeToDocumentScreen(documentUIModel: DocumentUIModel) {
        
    }
    

}
