//
//  DocumentListRouter.swift
//  ViperDemo
//
//  Created Thinh Nguyen on 12/3/17.
//  Copyright © 2017 Prospertin. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DocumentListRouter: DocumentListWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let mainStoryboard = UIStoryboard(name: "Main", bundle: Bundle.main);
        let navController = mainStoryboard.instantiateViewController(withIdentifier: "ViperNavigationController")
        if let view = navController.childViewControllers.first as? DocumentListViewController {
            let interactor = DocumentListInteractor()
            let router = DocumentListRouter()
            let presenter = DocumentListPresenter(view: view, interactor: interactor, router: router)
            let dataManager: DataManagerInputProtocol = DocumentDataManager()
            
            view.presenter = presenter
            interactor.presenter = presenter
            interactor.dataManager = dataManager
            router.viewController = view
            dataManager.interactor = interactor
        }
        return navController
    }
    /* DocumentListWireframeProtocol */
    func routeToDocumentScreen(documentUIModel: DocumentUIModel) {
        
    }
    

}
